<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Link macro -->
  <xacro:macro name="link_cylinder" params="name length radius mass material">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="${material}"/>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </visual>

      <collision>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </collision>

      <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <inertia
          ixx="0.01" iyy="0.01" izz="0.01"
          ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
    </link>
  </xacro:macro>

</robot>
